///*
//import java.awt.AlphaComposite;
//import java.awt.BasicStroke;
//import java.awt.Color;
//import java.awt.GradientPaint;
//import java.awt.Graphics;
//import java.awt.Graphics2D;
//import java.awt.Image;
//import java.awt.Rectangle;
//import java.awt.TexturePaint;
//import java.awt.image.BufferedImage;
//import java.awt.image.RenderedImage;
//import java.awt.print.*;
//import java.io.File;
//import java.io.FileOutputStream;
//import java.io.IOException;
//import java.io.ObjectOutputStream;
//import java.net.MalformedURLException;
//import java.net.URL;
//import java.util.HashSet;
//import java.util.Vector;
//import java.util.logging.Level;
//import java.util.logging.Logger;
//import javax.imageio.ImageIO;
//import javax.swing.ImageIcon;
//import javax.swing.JFileChooser;
//import javax.swing.JColorChooser;
//
///*
// * To change this template, choose Tools | Templates
// * and open the template in the editor.
// */
//
///**
// *
// * @author Marcus
// */
//public class Part1 extends javax.swing.JFrame {
//
//    /**
//     * Creates new form Part1
//     */
//    public Part1() {
//        initComponents();
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
//    private void initComponents() {
//
//        jLabel2 = new javax.swing.JLabel();
//        jPanel2 = new javax.swing.JPanel();
//        jPanel6 = new javax.swing.JPanel();
//        jPanel3 = new javax.swing.JPanel();
//        jSlider2 = new javax.swing.JSlider();
//        jPanel4 = new javax.swing.JPanel();
//        jSlider1 = new javax.swing.JSlider();
//        jPanel5 = new javax.swing.JPanel();
//        jSlider3 = new javax.swing.JSlider();
//        jPanel7 = new javax.swing.JPanel();
//        jSlider4 = new javax.swing.JSlider();
//        jLabel3 = new javax.swing.JLabel();
//        jPanel1 = new javax.swing.JPanel();
//        jPanel8 = new javax.swing.JPanel();
//        jToolBar1 = new javax.swing.JToolBar();
//        myOvalButton2 = new MyOvalButton();
//        myRectButton1 = new MyRectButton();
//        myRoundRectButton1 = new MyRoundRectButton();
//        myLineButton1 = new MyLineButton();
//        jButton6 = new javax.swing.JButton();
//        jCheckBox1 = new javax.swing.JCheckBox();
//        jCheckBox2 = new javax.swing.JCheckBox();
//        jToggleButton1 = new javax.swing.JToggleButton();
//        jToggleButton2 = new javax.swing.JToggleButton();
//        jLabel1 = new javax.swing.JLabel();
//        jSlider5 = new javax.swing.JSlider();
//        jButton8 = new javax.swing.JButton();
//        jTextField1 = new javax.swing.JTextField();
//        jToolBar2 = new javax.swing.JToolBar();
//        jButton3 = new javax.swing.JButton();
//        jButton2 = new javax.swing.JButton();
//        jButton11 = new javax.swing.JButton();
//        jButton1 = new javax.swing.JButton();
//        jButton5 = new javax.swing.JButton();
//        jButton9 = new javax.swing.JButton();
//        jMenuBar1 = new javax.swing.JMenuBar();
//        jMenu1 = new javax.swing.JMenu();
//        jMenu2 = new javax.swing.JMenu();
//        jMenuItem6 = new javax.swing.JMenuItem();
//        jMenu3 = new javax.swing.JMenu();
//        jMenuItem8 = new javax.swing.JMenuItem();
//        jMenuItem9 = new javax.swing.JMenuItem();
//        jMenuItem3 = new javax.swing.JMenuItem();
//        jMenuItem4 = new javax.swing.JMenuItem();
//        jMenuItem5 = new javax.swing.JMenuItem();
//
//        jLabel2.setText("jLabel2");
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//        setPreferredSize(new java.awt.Dimension(1250, 750));
//        addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mousePressed(java.awt.event.MouseEvent evt) {
//                formMousePressed(evt);
//            }
//        });
//        getContentPane().setLayout(new java.awt.BorderLayout());
//
//        jPanel2.setPreferredSize(new java.awt.Dimension(400, 70));
//        jPanel2.setLayout(new java.awt.GridLayout(1, 0));
//
//        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
//        jPanel6.setLayout(jPanel6Layout);
//        jPanel6Layout.setHorizontalGroup(
//            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 258, Short.MAX_VALUE)
//        );
//        jPanel6Layout.setVerticalGroup(
//            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 70, Short.MAX_VALUE)
//        );
//
//        jPanel2.add(jPanel6);
//
//        jPanel3.setBackground(new java.awt.Color(255, 0, 0));
//        jPanel3.setPreferredSize(new java.awt.Dimension(220, 50));
//
//        jSlider2.setBackground(new java.awt.Color(255, 0, 0));
//        jSlider2.setMajorTickSpacing(50);
//        jSlider2.setMaximum(255);
//        jSlider2.setMinorTickSpacing(10);
//        jSlider2.setPaintLabels(true);
//        jSlider2.setPaintTicks(true);
//        jSlider2.setValue(0);
//        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
//            public void stateChanged(javax.swing.event.ChangeEvent evt) {
//                jSlider2StateChanged(evt);
//            }
//        });
//
//        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
//        jPanel3.setLayout(jPanel3Layout);
//        jPanel3Layout.setHorizontalGroup(
//            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel3Layout.createSequentialGroup()
//                .addContainerGap()
//                .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addContainerGap(48, Short.MAX_VALUE))
//        );
//        jPanel3Layout.setVerticalGroup(
//            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
//                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(28, 28, 28))
//        );
//
//        jPanel2.add(jPanel3);
//
//        jPanel4.setBackground(new java.awt.Color(0, 255, 0));
//
//        jSlider1.setBackground(new java.awt.Color(0, 255, 0));
//        jSlider1.setMajorTickSpacing(50);
//        jSlider1.setMaximum(255);
//        jSlider1.setMinorTickSpacing(10);
//        jSlider1.setPaintLabels(true);
//        jSlider1.setPaintTicks(true);
//        jSlider1.setValue(0);
//        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
//            public void stateChanged(javax.swing.event.ChangeEvent evt) {
//                jSlider1StateChanged(evt);
//            }
//        });
//
//        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
//        jPanel4.setLayout(jPanel4Layout);
//        jPanel4Layout.setHorizontalGroup(
//            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
//                .addContainerGap(48, Short.MAX_VALUE)
//                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addContainerGap())
//        );
//        jPanel4Layout.setVerticalGroup(
//            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
//                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(27, 27, 27))
//        );
//
//        jPanel2.add(jPanel4);
//
//        jPanel5.setBackground(new java.awt.Color(0, 0, 255));
//
//        jSlider3.setBackground(new java.awt.Color(0, 0, 255));
//        jSlider3.setMajorTickSpacing(50);
//        jSlider3.setMaximum(255);
//        jSlider3.setMinorTickSpacing(10);
//        jSlider3.setPaintLabels(true);
//        jSlider3.setPaintTicks(true);
//        jSlider3.setValue(0);
//        jSlider3.addChangeListener(new javax.swing.event.ChangeListener() {
//            public void stateChanged(javax.swing.event.ChangeEvent evt) {
//                jSlider3StateChanged(evt);
//            }
//        });
//
//        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
//        jPanel5.setLayout(jPanel5Layout);
//        jPanel5Layout.setHorizontalGroup(
//            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
//                .addContainerGap(48, Short.MAX_VALUE)
//                .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addContainerGap())
//        );
//        jPanel5Layout.setVerticalGroup(
//            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
//                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(25, 25, 25))
//        );
//
//        jPanel2.add(jPanel5);
//
//        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
//
//        jSlider4.setMajorTickSpacing(20);
//        jSlider4.setMinorTickSpacing(5);
//        jSlider4.setPaintLabels(true);
//        jSlider4.setPaintTicks(true);
//        jSlider4.setValue(10);
//        jSlider4.addChangeListener(new javax.swing.event.ChangeListener() {
//            public void stateChanged(javax.swing.event.ChangeEvent evt) {
//                jSlider4StateChanged(evt);
//            }
//        });
//
//        jLabel3.setText("Stroke Width:");
//
//        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
//        jPanel7.setLayout(jPanel7Layout);
//        jPanel7Layout.setHorizontalGroup(
//            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
//                .addContainerGap()
//                .addComponent(jSlider4, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
//                .addContainerGap())
//            .addGroup(jPanel7Layout.createSequentialGroup()
//                .addGap(92, 92, 92)
//                .addComponent(jLabel3)
//                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//        );
//        jPanel7Layout.setVerticalGroup(
//            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
//                .addGap(0, 5, Short.MAX_VALUE)
//                .addComponent(jLabel3)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(jSlider4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//        );
//
//        jPanel2.add(jPanel7);
//
//        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);
//
//        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mouseReleased(java.awt.event.MouseEvent evt) {
//                jPanel1MouseReleased(evt);
//            }
//            public void mousePressed(java.awt.event.MouseEvent evt) {
//                jPanel1MousePressed(evt);
//            }
//        });
//        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
//            public void componentResized(java.awt.event.ComponentEvent evt) {
//                jPanel1ComponentResized(evt);
//            }
//        });
//        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
//            public void mouseDragged(java.awt.event.MouseEvent evt) {
//                jPanel1MouseDragged(evt);
//            }
//        });
//
//        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//        jPanel1.setLayout(jPanel1Layout);
//        jPanel1Layout.setHorizontalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 1290, Short.MAX_VALUE)
//        );
//        jPanel1Layout.setVerticalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 271, Short.MAX_VALUE)
//        );
//
//        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
//
//        jPanel8.setMaximumSize(new java.awt.Dimension(100, 80));
//        jPanel8.setPreferredSize(new java.awt.Dimension(100, 80));
//
//        jToolBar1.setRollover(true);
//
//        myOvalButton2.setFocusable(false);
//        myOvalButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
//        myOvalButton2.setPreferredSize(new java.awt.Dimension(30, 30));
//        myOvalButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
//        myOvalButton2.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                myOvalButton2ActionPerformed(evt);
//            }
//        });
//        jToolBar1.add(myOvalButton2);
//
//        myRectButton1.setFocusable(false);
//        myRectButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
//        myRectButton1.setPreferredSize(new java.awt.Dimension(30, 30));
//        myRectButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
//        myRectButton1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                myRectButton1ActionPerformed(evt);
//            }
//        });
//        jToolBar1.add(myRectButton1);
//
//        myRoundRectButton1.setFocusable(false);
//        myRoundRectButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
//        myRoundRectButton1.setPreferredSize(new java.awt.Dimension(30, 30));
//        myRoundRectButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
//        myRoundRectButton1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                myRoundRectButton1ActionPerformed(evt);
//            }
//        });
//        jToolBar1.add(myRoundRectButton1);
//
//        myLineButton1.setFocusable(false);
//        myLineButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
//        myLineButton1.setPreferredSize(new java.awt.Dimension(30, 30));
//        myLineButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
//        myLineButton1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                myLineButton1ActionPerformed(evt);
//            }
//        });
//        jToolBar1.add(myLineButton1);
//
//        jButton6.setText("FreeHand");
//        jButton6.setFocusable(false);
//        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
//        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
//        jButton6.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton6ActionPerformed(evt);
//            }
//        });
//        jToolBar1.add(jButton6);
//
//        jCheckBox1.setText("dashed");
//        jCheckBox1.setFocusable(false);
//        jCheckBox1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
//        jCheckBox1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
//        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jCheckBox1ActionPerformed(evt);
//            }
//        });
//        jToolBar1.add(jCheckBox1);
//
//        jCheckBox2.setText("Filled");
//        jCheckBox2.setFocusable(false);
//        jCheckBox2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
//        jCheckBox2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
//        jToolBar1.add(jCheckBox2);
//
//        jToggleButton1.setText("Set Gradient");
//        jToggleButton1.setFocusable(false);
//        jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
//        jToggleButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
//        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jToggleButton1ActionPerformed(evt);
//            }
//        });
//        jToolBar1.add(jToggleButton1);
//
//        jToggleButton2.setText("Set Texture");
//        jToggleButton2.setFocusable(false);
//        jToggleButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
//        jToggleButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
//        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jToggleButton2ActionPerformed(evt);
//            }
//        });
//        jToolBar1.add(jToggleButton2);
//
//        jLabel1.setText("Transparency: ");
//        jToolBar1.add(jLabel1);
//
//        jSlider5.setBackground(new java.awt.Color(245, 245, 245));
//        jSlider5.setValue(100);
//        jSlider5.addChangeListener(new javax.swing.event.ChangeListener() {
//            public void stateChanged(javax.swing.event.ChangeEvent evt) {
//                jSlider5StateChanged(evt);
//            }
//        });
//        jToolBar1.add(jSlider5);
//
//        jButton8.setText("Place Text: ");
//        jButton8.setFocusable(false);
//        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
//        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
//        jButton8.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton8ActionPerformed(evt);
//            }
//        });
//        jToolBar1.add(jButton8);
//
//        jTextField1.setPreferredSize(new java.awt.Dimension(100, 30));
//        jToolBar1.add(jTextField1);
//
//        jToolBar2.setRollover(true);
//
//        jButton3.setText("Open as Object");
//        jButton3.setFocusable(false);
//        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
//        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
//        jButton3.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton3ActionPerformed(evt);
//            }
//        });
//        jToolBar2.add(jButton3);
//
//        jButton2.setText("Save as Object");
//        jButton2.setFocusable(false);
//        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
//        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
//        jButton2.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton2ActionPerformed(evt);
//            }
//        });
//        jToolBar2.add(jButton2);
//
//        jButton11.setText("Save as Image");
//        jButton11.setFocusable(false);
//        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
//        jButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
//        jButton11.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton11ActionPerformed(evt);
//            }
//        });
//        jToolBar2.add(jButton11);
//
//        jButton1.setText("Print");
//        jButton1.setFocusable(false);
//        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
//        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
//        jButton1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton1ActionPerformed(evt);
//            }
//        });
//        jToolBar2.add(jButton1);
//
//        jButton5.setText("Clear");
//        jButton5.setFocusable(false);
//        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
//        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
//        jButton5.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton5ActionPerformed(evt);
//            }
//        });
//        jToolBar2.add(jButton5);
//
//        jButton9.setText("Exit");
//        jButton9.setFocusable(false);
//        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
//        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
//        jButton9.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton9ActionPerformed(evt);
//            }
//        });
//        jToolBar2.add(jButton9);
//
//        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
//        jPanel8.setLayout(jPanel8Layout);
//        jPanel8Layout.setHorizontalGroup(
//            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1290, Short.MAX_VALUE)
//            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//        );
//        jPanel8Layout.setVerticalGroup(
//            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel8Layout.createSequentialGroup()
//                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(0, 0, 0)
//                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//        );
//
//        getContentPane().add(jPanel8, java.awt.BorderLayout.PAGE_START);
//
//        jMenu1.setText("File");
//
//        jMenu2.setText("Open");
//
//        jMenuItem6.setText("as Object");
//        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jMenuItem6ActionPerformed(evt);
//            }
//        });
//        jMenu2.add(jMenuItem6);
//
//        jMenu1.add(jMenu2);
//
//        jMenu3.setText("Save");
//
//        jMenuItem8.setText("as Object");
//        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jMenuItem8ActionPerformed(evt);
//            }
//        });
//        jMenu3.add(jMenuItem8);
//
//        jMenuItem9.setText("as Image");
//        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jMenuItem9ActionPerformed(evt);
//            }
//        });
//        jMenu3.add(jMenuItem9);
//
//        jMenu1.add(jMenu3);
//
//        jMenuItem3.setText("Print");
//        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jMenuItem3ActionPerformed(evt);
//            }
//        });
//        jMenu1.add(jMenuItem3);
//
//        jMenuItem4.setText("Clear");
//        jMenu1.add(jMenuItem4);
//
//        jMenuItem5.setText("Exit");
//        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jMenuItem5ActionPerformed(evt);
//            }
//        });
//        jMenu1.add(jMenuItem5);
//
//        jMenuBar1.add(jMenu1);
//
//        setJMenuBar(jMenuBar1);
//
//        pack();
//    }// </editor-fold>                        
//
//    Image bg, fg;
//    Brush b, rebrush;
//    
//    boolean dashed;
//    boolean filled;
//
//    
//    //gradient, texture, and alpha vars
//    boolean gradientToggled;
//    boolean textureToggled;
//    float alphaVal = 1;
//    Color gA = Color.black;
//    Color gB =  Color.black;
//    BufferedImage bi;
//    Rectangle r;
//
//    //drawn shape variables
//    int strokeSize = 10;
//    int oldx, oldy;
//    int newx, newy; 
//    int type; //used when adding shapes to the vector because graphics are not serializable
//    String text = "";
//    Vector<Shape> v = new Vector<Shape>();
//  
//    
//    public void paint(Graphics g){
//        super.paint(g);
//        Graphics pg = jPanel1.getGraphics();
//        bg = jPanel1.createImage(jPanel1.getWidth(), jPanel1.getHeight());
//        fg = jPanel1.createImage(jPanel1.getWidth(), jPanel1.getHeight());
//        
//        Graphics fgg = fg.getGraphics();
//        //fgg.drawImage(bg, 0, 0, null);
//        Graphics2D f2d = (Graphics2D) fgg;
//        
//        //redraw all shapes stored in vector
//        for (int i = 0; i< v.size(); i++){
//            
//            Shape s = v.elementAt(i);
//            
//            if (!s.gradientToggled && !s.textureToggled){
//                Color c = new Color(s.red, s.green, s.blue);
//                f2d.setColor(c);
//            }
//            else if(s.textureToggled){
//                bi = new BufferedImage(75, 75, BufferedImage.TYPE_4BYTE_ABGR);
//                r = new Rectangle(75, 75);
//                Graphics big = bi.createGraphics();
//                big.setColor(Color.red);
//                big.fillOval(0, 0, 50, 50);
//                TexturePaint tp = new TexturePaint(bi, r);
//                f2d.setPaint(tp);
//            }
//            else {
//               GradientPaint gp = new GradientPaint(0,0,new Color(s.gBRed,s.gBGreen,s.gBBlue),0,this.getHeight(), new Color(s.gARed,s.gAGreen,s.gABlue));
//               f2d.setPaint(gp);
//            }
//        
//            AlphaComposite ac = AlphaComposite.getInstance(AlphaComposite.SRC_OVER, s.alphaVal);
//            f2d.setComposite(ac);
//
//            
//            if (s.type == 0)
//                rebrush = new Oval();
//            else if (s.type == 1)
//                rebrush = new Rect();
//            else if (s.type == 2)
//                rebrush = new RoundRect();
//            else if (s.type == 3)
//                rebrush = new Line();
//            else if (s.type == 4)
//                rebrush = new Drag();
//            else if (s.type == 5)
//                rebrush = new Text();
//            
//            rebrush.draw(f2d, s.x1, s.y1, s.x2, s.y2, s.dashed, s.filled, s.strokeSize, s.text);
//        }
//            pg.drawImage(fg, 0, 0, null);
//            Graphics bgg = bg.getGraphics();
//            bgg.drawImage(fg, 0, 0, null);  
//    }
//    
//    
//    private void formMousePressed(java.awt.event.MouseEvent evt) {                                  
//        // TODO add your handling code here:
//    }                                 
//
//    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {                                      
//        // TODO add your handling code here:
//        jPanel6.setBackground(new Color(jSlider2.getValue(), jSlider1.getValue(), jSlider3.getValue()));
//    }                                     
//
//    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {                                      
//        // TODO add your handling code here:
//        jPanel6.setBackground(new Color(jSlider2.getValue(), jSlider1.getValue(), jSlider3.getValue()));
//    }                                     
//
//    private void jSlider3StateChanged(javax.swing.event.ChangeEvent evt) {                                      
//        // TODO add your handling code here:
//        jPanel6.setBackground(new Color(jSlider2.getValue(), jSlider1.getValue(), jSlider3.getValue()));
//        
//    }                                     
//
//    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {                                     
//        // TODO add your handling code here:
//        oldx = evt.getX();
//        oldy = evt.getY();
//        
//        if (bg == null){
//            bg = jPanel1.createImage(jPanel1.getWidth(), jPanel1.getHeight());
//            fg = jPanel1.createImage(jPanel1.getWidth(), jPanel1.getHeight());
//        }
//        
//    }                                    
//
//    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {                                      
//        // TODO add your handling code here:
//
//        //store drawn shapes
//        v.add(new Shape(type, oldx, oldy, evt.getX(), evt.getY(), jSlider2.getValue(), jSlider1.getValue(), jSlider3.getValue(), dashed, filled, strokeSize, gradientToggled, textureToggled, text, gA.getRed(), gA.getGreen(), gA.getBlue(), gB.getRed(), gB.getGreen(), gB.getBlue(), alphaVal));
//        
//        //draw foreground to background
//        Graphics bgg = bg.getGraphics();
//        bgg.drawImage(fg, 0, 0, null);
//    
//    }                                     
//
//    private void jPanel1ComponentResized(java.awt.event.ComponentEvent evt) {                                         
//        // TODO add your handling code here:
//        
//        //repaints shapes
//        repaint();
//    }                                        
//
//    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
//        // TODO add your handling code here:
//        
//        //clears canvas
//        /*cleared shapes no longer reappear when resizing however the images still do not resize and present shapes sometimes switch
//         from solid to dashed lines on resize so it is still not supported*/
//        v.clear();
//        Graphics bgg = bg.getGraphics();
//        bgg.clearRect(0, 0, this.getWidth(), this.getHeight());
//        repaint();
//    }                                        
//
//    private void myOvalButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                              
//        // TODO add your handling code here:
//        b = new Oval();
//        type = 0;
//    }                                             
//
//    private void myRectButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
//        // TODO add your handling code here:
//        b = new Rect();
//        type = 1;
//    }                                             
//
//    private void myRoundRectButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                                   
//        // TODO add your handling code here:
//        b = new RoundRect();
//        type = 2;
//    }                                                  
//
//    private void myLineButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
//        // TODO add your handling code here:
//        b = new Line();
//        type = 3;
//    }                                             
//
//    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {                                     
//        // TODO add your handling code here:
//        
//        //draw background on foreground
//        Graphics fgg = fg.getGraphics();
//        fgg.drawImage(bg, 0, 0, null);
//        
//        //draw to foreground
//        
//        Graphics2D f2d = (Graphics2D) fgg;
//        
//        //set the color, gradient, or texture (as in the example texture takes precedence over gradient)
//        if (!gradientToggled && !textureToggled){
//            Color c = new Color(jSlider2.getValue(), jSlider1.getValue(), jSlider3.getValue());
//            f2d.setColor(c);
//        }
//        else if(textureToggled){
//            bi = new BufferedImage(75, 75, BufferedImage.TYPE_4BYTE_ABGR);
//            r = new Rectangle(75, 75);
//            Graphics big = bi.createGraphics();
//            big.setColor(Color.red);
//            big.fillOval(0, 0, 50, 50);
//            TexturePaint tp = new TexturePaint(bi, r);
//            f2d.setPaint(tp);
//        }
//        else {
//            GradientPaint gp = new GradientPaint(0,0,gB,0,this.getHeight(), gA);
//            f2d.setPaint(gp);
//        }
//        
//        AlphaComposite ac = AlphaComposite.getInstance(AlphaComposite.SRC_OVER, alphaVal);
//        f2d.setComposite(ac);
//        
//        //check if the shape is dashed or filled
//        if (jCheckBox1.isSelected())
//            dashed = true;
//        else
//            dashed = false;
//        
//        if (jCheckBox2.isSelected())
//            filled = true;
//        else
//            filled = false;
//        
//        //draw shapes except for the pencil tool
//        if (type != 4)
//            b.draw(f2d, oldx, oldy, evt.getX(), evt.getY(), dashed, filled, strokeSize, text);
//        
//        //draw using the pencil tool
//        if (type == 4){
//        //    if(evt.getX() - oldx < 10 && evt.getY() - oldy < 10)
//           b.draw(f2d, oldx, oldy, evt.getX(), evt.getY(), dashed, filled, strokeSize, text);
//           Graphics bgg = bg.getGraphics();
//           bgg.drawImage(fg, 0, 0, null);
//           v.add(new Shape(type, oldx, oldy, evt.getX(), evt.getY(), jSlider2.getValue(), jSlider1.getValue(), jSlider3.getValue(), dashed, filled, strokeSize, gradientToggled, textureToggled, text, gA.getRed(), gA.getGreen(), gA.getBlue(), gB.getRed(), gB.getGreen(), gB.getBlue(), alphaVal));
//           oldx = evt.getX();
//           oldy = evt.getY();
//        }
//
//        //}
//        
//        
//        Graphics g = jPanel1.getGraphics();
//        g.drawImage(fg, 0, 0, null);
//    }                                    
//
//    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
//        // TODO add your handling code here:
//    }                                          
//
//    //ImageIcon ii;
//    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
//        // set up printing from tool bar button
//        PrinterJob pj = PrinterJob.getPrinterJob();
//        PageFormat pf = pj.pageDialog(new PageFormat());
//        if(pj.printDialog()){
//            
//            Book bo = new Book();
//            Printable printable = new MyPrintable(bg);
//            bo.append(printable, pf);
//            
//            pj.setPageable(bo);
//            try{
//                pj.print();
//            } catch (PrinterException ex) {
//                Logger.getLogger(Part1.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            }
//    
//    }                                        
//
//    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
//        // Toolbar save as object
//        ObjectSave os = new ObjectSave();
//        try {
//            os.save(v);
//        } catch (Exception ex) {
//            Logger.getLogger(Part1.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        
//    }                                        
//
//    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
//        // Toolbar open Object
//        ObjectOpen oo = new ObjectOpen();
//        try {
//            v = oo.openShapeVector();
//        } catch (Exception ex) {
//            Logger.getLogger(Part1.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        repaint();
//    }                                        
//
//    private void jSlider4StateChanged(javax.swing.event.ChangeEvent evt) {                                      
//        // TODO add your handling code here:
//        strokeSize = jSlider4.getValue();
//    }                                     
//
//    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
//        // create new drag(pencil style drawing)
//        b = new Drag();
//        type = 4;
//    }                                        
//
//    private void jSlider5StateChanged(javax.swing.event.ChangeEvent evt) {                                      
//        // TODO add your handling code here:
//        alphaVal = (jSlider5.getValue())/100.0f;
//        //repaint();
//    }                                     
//
//    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
//        // TODO add your handling code here:
//        text = jTextField1.getText();
//        type = 5;
//        b = new Text();
//    }                                        
//
//    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
//        // TODO add your handling code here:
//        System.exit(1);
//    }                                        
//
//    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {                                           
//        // TODO add your handling code here:
//        System.exit(1);
//    }                                          
//
//    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
//        // set up printing from file -> print button
//        PrinterJob pj = PrinterJob.getPrinterJob();
//        PageFormat pf = pj.pageDialog(new PageFormat());
//        if(pj.printDialog()){
//            
//            Book bo = new Book();
//            Printable printable = new MyPrintable(bg);
//            bo.append(printable, pf);
//            
//            pj.setPageable(bo);
//            try{
//                pj.print();
//            } catch (PrinterException ex) {
//                Logger.getLogger(Part1.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            }
//    }                                          
//
//    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {                                           
//        // file -> open -> as object same as toolbar version
//        ObjectOpen oo = new ObjectOpen();
//        try {
//            v = oo.openShapeVector();
//        } catch (Exception ex) {
//            Logger.getLogger(Part1.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        repaint();
//    }                                          
//
//    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {                                           
//        // file -> save -> as Object same as toolbar version
//        ObjectSave os = new ObjectSave();
//        try {
//            os.save(v);
//        } catch (Exception ex) {
//            Logger.getLogger(Part1.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }                                          
//
//    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {                                          
//        // Toolbar save as image
//        ImageSave is = new ImageSave();
//        try {
//            is.save((BufferedImage) bg);
//        } catch (Exception ex) {
//            Logger.getLogger(Part1.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }                                         
//
//    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {                                           
//        // file -> save -> as image
//        ImageSave is = new ImageSave();
//        try {
//            is.save((BufferedImage) bg);
//        } catch (Exception ex) {
//            Logger.getLogger(Part1.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }                                          
//
//    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                               
//        // Set Gradient
//        if(!gradientToggled){
//            gA = JColorChooser.showDialog(this, "First Color Selector", null);
//            gB = JColorChooser.showDialog(this, "Second Color Selector", null);
//            gradientToggled = true;
//        }
//        else{
//            gA = jPanel6.getBackground();
//            gB = jPanel6.getBackground();
//            gradientToggled = false;
//        }
//    }                                              
//
//    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                               
//        // toggles whether to use image texture when painting
//        if(!textureToggled){
//            textureToggled = true;
//        }
//        else
//            textureToggled = false;
//    }                                              
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Part1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Part1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Part1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Part1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Part1().setVisible(true);
//            }
//        });
//    }
//    // Variables declaration - do not modify                     
//    private javax.swing.JButton jButton1;
//    private javax.swing.JButton jButton11;
//    private javax.swing.JButton jButton2;
//    private javax.swing.JButton jButton3;
//    private javax.swing.JButton jButton5;
//    private javax.swing.JButton jButton6;
//    private javax.swing.JButton jButton8;
//    private javax.swing.JButton jButton9;
//    private javax.swing.JCheckBox jCheckBox1;
//    private javax.swing.JCheckBox jCheckBox2;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JLabel jLabel3;
//    private javax.swing.JMenu jMenu1;
//    private javax.swing.JMenu jMenu2;
//    private javax.swing.JMenu jMenu3;
//    private javax.swing.JMenuBar jMenuBar1;
//    private javax.swing.JMenuItem jMenuItem3;
//    private javax.swing.JMenuItem jMenuItem4;
//    private javax.swing.JMenuItem jMenuItem5;
//    private javax.swing.JMenuItem jMenuItem6;
//    private javax.swing.JMenuItem jMenuItem8;
//    private javax.swing.JMenuItem jMenuItem9;
//    private javax.swing.JPanel jPanel1;
//    private javax.swing.JPanel jPanel2;
//    private javax.swing.JPanel jPanel3;
//    private javax.swing.JPanel jPanel4;
//    private javax.swing.JPanel jPanel5;
//    private javax.swing.JPanel jPanel6;
//    private javax.swing.JPanel jPanel7;
//    private javax.swing.JPanel jPanel8;
//    private javax.swing.JSlider jSlider1;
//    private javax.swing.JSlider jSlider2;
//    private javax.swing.JSlider jSlider3;
//    private javax.swing.JSlider jSlider4;
//    private javax.swing.JSlider jSlider5;
//    private javax.swing.JTextField jTextField1;
//    private javax.swing.JToggleButton jToggleButton1;
//    private javax.swing.JToggleButton jToggleButton2;
//    private javax.swing.JToolBar jToolBar1;
//    private javax.swing.JToolBar jToolBar2;
//    private MyLineButton myLineButton1;
//    private MyOvalButton myOvalButton2;
//    private MyRectButton myRectButton1;
//    private MyRoundRectButton myRoundRectButton1;
//    // End of variables declaration                   
//}

