/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Calendar_And_Tasks;

import com.google.gdata.data.calendar.CalendarEventEntry;
import com.google.gdata.data.extensions.When;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

/**
 *
 * @author mak5278
 */
public class EventPanel extends javax.swing.JPanel {

    /**
     * Creates new form EventPanel
     * @param myEntry
     */
    public EventPanel(CalendarEventEntry myEntry) {
        initComponents();
        jLabel1.setText(myEntry.getTitle().getPlainText());
        jLabel2.setText(myEntry.getLocations().get(0).getValueString());
        jLabel3.setText(myEntry.getSummary().getPlainText());
        
        SimpleDateFormat sdf = new SimpleDateFormat("MM/DD/YYYY");
        SimpleDateFormat sdf1 = new SimpleDateFormat("h:mm a");
        List<When> times = myEntry.getTimes();
        Time t = new Time(times.get(0).getStartTime().getValue());
        jLabel4.setText(sdf1.format(t));
        
        t = new Time(times.get(0).getEndTime().getValue());
        jLabel5.setText(sdf1.format(t));
        
        Date date = new Date(t.getTime());
        jLabel6.setText(sdf.format(date));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout());

        jLabel1.setText("jLabel1");
        add(jLabel1);

        jLabel2.setText("jLabel2");
        add(jLabel2);

        jLabel3.setText("jLabel3");
        add(jLabel3);

        jLabel4.setText("jLabel4");
        add(jLabel4);

        jLabel5.setText("jLabel5");
        add(jLabel5);

        jLabel6.setText("jLabel6");
        add(jLabel6);

        jButton1.setText("Edit");
        add(jButton1);

        jButton2.setText("Delete");
        add(jButton2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
