/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Calendar_And_Tasks;

import com.google.gdata.data.calendar.CalendarEventEntry;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author mak5278
 */
public class ViewEventsFrame extends JFrame {

    private JButton close;
    private JPanel aPanel;
    
    /**
     * Creates new form viewEventsPanel
     * @param ceeArrayList
     */
    public ViewEventsFrame(ArrayList<CalendarEventEntry> ceeArrayList) {
        super("Event Descriptions");
        initComponents();
        close = new JButton("Close");
        aPanel = new JPanel();
        aPanel.setLayout(new GridLayout(ceeArrayList.size()+1,1));
        
        close.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                setVisible(false);
            }
        });
        
        
        for (int i = 0; i < ceeArrayList.size(); i++){
            EventPanel ep = new EventPanel(ceeArrayList.get(i));
            aPanel.add(ep);
        }
        
        close = new JButton("Close");
        aPanel.add(close);
        
        aPanel.setSize(aPanel.getPreferredSize());
        
        this.add(aPanel);
        this.setSize(500,100);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
